stages:
  - deploy

pages:
  stage: deploy
  image: alpine:3.20
  tags:
    - os/linux
    - cpu/x86_64
    - type/docker
  script:
    - mkdir -p public
    - cp sol_calculator.html public/index.html
    - cp sol_calculator.html public/sol_calculator.html
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
